import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/next-themes";
import FirsPage from "./page";
import { Pagina_Dash } from "./pages/dashboard";

// Fontes locais
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadados
export const metadata: Metadata = {
  title: "Pleno Sol",
  description: "Generated by create next app",
};

// RootLayout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider attribute="class">
          {/* Renderiza o conteúdo passado como children */}
          <FirsPage/>

        </ThemeProvider>
      </body>
    </html>
  );
}
