import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/next-themes";
import FirsPage from "./page";
import { Pagina_Dash } from "./pages/dashboard";





const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
    <head />
    <body>

      <ThemeProvider attribute="class">
        <FirsPage/>
        <Pagina_Dash/>
      </ThemeProvider>
      

    </body>
  </html>
  
  
  );
}
